### PR TITLE
Type to Select improvements

### PR DESCRIPTION
**Pull request by rmottola**
https://github.com/gnustep/apps-gworkspace/issues/31

### CODE REVIEW

**Comment by rmottola** [comment]
@rfm @fredkiefer how would you call this "type select" behaviour? maybe I can rename some of the related variables better, I already tried a little bit.
typeSelect is what I would use currently.

**Comment by rmottola** [comment]
@eukara this works starts from your "Escape" patch, so if you care to test or comment on it, welcome.

**Comment by eukara** [comment]
Testing it now.

**Comment by eukara** [comment]
All good on my end.

**Comment by rmottola** [comment]
Thank you, @eukara

**Pull request merged**
