### PR TITLE
Makefile and config changes to remove 'G' from Workspace

### PR DESCRIPTION
**Pull request by gcasa**
This PR makes a relatively minor change to GWorkspace.app to rename it to Workspace.app.   Take a look and let me know if there are any issues.

### CODE REVIEW

**Comment by gcasa** [comment]
Whoa, this was supposed to go against their fork, but I think we can consider it here.   Here's the thing... all of the other apps that have G in front of them have changed.  In GORM the G also stands for graphical, so that is not a counterexample.

**Comment by rmottola** [comment]
I am proud that of the G in GWorkspace, since it stands for GNU.

Also, after 20 years the name stuck, it is the name of all packages around, URLs, tutorials, so I think it is a bad idea do change it.

So I don't want to merge this. Not before an upcoming release anyway.

What's next, renaming GNUMail to Mail?

**Comment by gcasa** [comment]
> I am proud that of the G in GWorkspace, since it stands for GNU.
> 
> 
> 
> Also, after 20 years the name stuck, it is the name of all packages around, URLs, tutorials, so I think it is a bad idea do change it.
> 
> 
> 
> So I don't want to merge this. Not before an upcoming release anyway.
> 
> 
> 
> What's next, renaming GNUMail to Mail?

It doesn't stand for GNU it stands for GNUstep.  This is something that I specifically put a stop to early on as every app was coming out G this or G that and it looks and sounds idiotic.  I think it's silly to be attached to a letter in the name of the app. 

Regarding GNUmail, yes Mail would be better, but it isn't an official GNUstep application so I have no say.

**Comment by gcasa** [comment]
Also I have considered changing the name of Gorm any number of times as well to IC or InterfaceCreator.

**Comment by rmottola** [comment]
yes.. .and GNU in GNUstep isn't still GNU?
I think it is silly to have an issue with a G letter that identifies, especially on existing apps.
Unfortunately it is shared with Google and obviously with GNOME, but the latter tracks from GNU too...
KDE has K everywhere.

Also, GWorkspace and GNUMail are unique in their name, making it easy to look for them on the internet, try that with Workspace or Mail... if you are lucky you end and on Apple's but more probably in just generic sites, try Mail.app in a couple of search engines.

I thought in the past of just renaming the menu like I did with batmon & Battery Monitor... but inconsistency with the application name made me halt. KMail is KMail, but KWorkspace shows KDE Workspace.

**Comment by gcasa** [comment]
I am curious as to how many tutorials GWorkspace actually shows up in as it is not a dev tool. Closing due to the above objections.

**Comment by gcasa** [comment]
It looks so much more professional without the G.  But we can leave it GGGGGGGGGGGGGGGGGGGGGGWorkspace. ;)

**Pull request closed without merging**
